- name: copy config file to remote server
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root
  with_items:
    - { src: system/openresty.service.j2, dest: "/etc/systemd/system/openresty.service" }
    - { src: conf/nginx.conf.j2, dest: "{{ nginx_dir }}/conf/nginx.conf" }
    - { src: conf/cloudflare.conf, dest: "{{ nginx_dir }}/vhosts/cloudflare.conf" }
    - { src: conf/mainnet_whitelist.conf, dest: "{{ nginx_dir }}/conf.secure/mainnet_whitelist.conf" }
    - { src: conf/testnet_whitelist.conf, dest: "{{ nginx_dir }}/conf.secure/testnet_whitelist.conf" }
    - { src: logrotate/nginx.j2, dest: "/etc/logrotate.d/nginx" }

- name: copy modules file to remote server
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root
  with_items:
    - { src: ../templates/modules/, dest: "{{ modules_dir }}/" }
