- name: install yum packages
  yum: name={{ item }} state=present
  with_items:
    - pcre-devel
    - pcre
    - openssl-devel
    - openssl
    - zlib-devel
    - zlib
    - perl
    - gcc
    - geoip-devel
    - libmaxminddb-devel
  when: ansible_pkg_mgr == 'yum'

- name: install apt packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - libreadline-dev
    - libncurses5-dev
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - zlib1g-dev
    - libjemalloc-dev
    - perl
    - make
    - libgeoip1
    - libgeoip-dev
    - geoip-bin
    - libmaxminddb0
    - libmaxminddb-dev
    - mmdb-bin
  when: ansible_pkg_mgr == 'apt'

- name: configure openresty
  shell: "cd {{ download_dir }}/openresty-{{ rev }} && ./configure --prefix={{ prefix_dir }} --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-stream --with-http_ssl_module --with-http_geoip_module"

- name: make and make install - openresty
  shell: "cd {{ download_dir }}/openresty-{{ rev }} && make && make install"
